window.ODAYAMA_PRODUCTS = [
  {
    id: "gosyuin-tsujo",
    sku: "ODY-GOS-001",
    name: "通常御朱印",
    category: "御朱印",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "小田山神社の通常御朱印です。画像と初穂料は管理画面で登録できる想定です。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "通常御朱印の画像",
    sortOrder: 10,
  },
  {
    id: "gosyuin-kisetsu",
    sku: "ODY-GOS-002",
    name: "季節の御朱印",
    category: "御朱印",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "季節や行事に合わせた御朱印です。授与期間の管理にも対応しやすい商品データです。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "季節の御朱印の画像",
    sortOrder: 20,
  },
  {
    id: "omamori-kannai",
    sku: "ODY-OMA-001",
    name: "家内安全御守",
    category: "御守り",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "ご家庭の安全と日々の平穏を願う御守りです。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "家内安全御守の画像",
    sortOrder: 30,
  },
  {
    id: "omamori-kenko",
    sku: "ODY-OMA-002",
    name: "身体健全御守",
    category: "御守り",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "身体健全を願う御守りです。ご本人用、贈答用として登録できます。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "身体健全御守の画像",
    sortOrder: 40,
  },
  {
    id: "omamori-yakuyoke",
    sku: "ODY-OMA-003",
    name: "厄除御守",
    category: "御守り",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "厄除けを願う御守りです。厄年の方にも案内しやすい商品です。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "厄除御守の画像",
    sortOrder: 50,
  },
  {
    id: "omamori-kotsu",
    sku: "ODY-OMA-004",
    name: "交通安全御守",
    category: "御守り",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "日々の移動や車の安全を願う御守りです。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "交通安全御守の画像",
    sortOrder: 60,
  },
  {
    id: "kiganfuda-kannai",
    sku: "ODY-FDA-001",
    name: "家内安全祈願札",
    category: "祈願札",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "家内安全の祈願札です。祈願内容に応じて受付内容を確認できる想定です。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "家内安全祈願札の画像",
    sortOrder: 70,
  },
  {
    id: "kiganfuda-shobai",
    sku: "ODY-FDA-002",
    name: "商売繁盛祈願札",
    category: "祈願札",
    initialOffering: null,
    initialOfferingLabel: "後で入力",
    description: "商売繁盛を願う祈願札です。事業者名などの追加入力にも拡張できます。",
    fulfillment: "郵送対応",
    status: "available",
    statusLabel: "授与可",
    image: "",
    imageAlt: "商売繁盛祈願札の画像",
    sortOrder: 80,
  },
];
